[package]
name = "vlcrs-macros"
edition = "2021"
version.workspace = true
license.workspace = true

[lib]
proc-macro = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(vlc_static_plugins)'] }

[dependencies]
vlcrs-core = { path = "../vlcrs-core" }
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
proc-macro2 = "1.0"
