[package]
name = "vlcrs-core"
edition = "2021"
version.workspace = true
license.workspace = true

[dependencies]
vlcrs-messages = { path = "../vlcrs-messages" }

[dev-dependencies]
vlcrs-macros.workspace = true
